Repository entando/entando-core-parent, pull requests merged in 2021-04, with the labels that each got.

#11 ENG-2259 Fix the entando-core-parent vulnarable dependencies
  pom.xml
Labels: size/S

#12 #ENG-2259 found compatible spring/jackson combination
  pom.xml
Labels: approved, size/XS

#13 ENG-2261: upgrade velocity version
  pom.xml
Labels: approved, size/S

#14 ENG-2259 Fix the app-engine vulnarable dependencies
  owasp-dependency-check-suppression.xml
  pom.xml
Labels: approved, size/S

#15 ENG-2197 update common-io version to non vulnerable version
  pom.xml
Labels: approved, size/XS

#16 ENG-2029: Added logback dependency
  pom.xml
Labels: approved, size/S

#17 Revert "ENG-2029: Added logback dependency"
  pom.xml
Labels: size/S

#18 ENG-2029: Added logback dependency
  pom.xml
Labels: approved, size/M
