Repository entando/entando-core-parent, pull requests merged in 2021-07, with the labels that each got.

#27 ENG-2178 Adding dependency to fix swagger doc
  pom.xml
Labels: approved, size/XS

#28 ENG-2178 Rolling back swagger version update due to inconsistencies i…
  pom.xml
Labels: size/XS

#30 ENG-2178 Updating swagger version
  pom.xml
Labels: size/XS

#31 ENG-2552: Remove Argon2 dependency
  pom.xml
Labels: size/XS

#32 ENG-2471 new gen workflow v1.0.1
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
Labels: prepared, size/L

#33 ENG-2471 v1.0.1 fix ga-pub
  pom.xml
Labels: prepared

#34 ENG-2471 local aux project for scans
  pom.xml
  scan-prj/build-pom.sh
  scan-prj/pom.xml
  scan-prj/pom.xml.tpl
Labels: prepared

#41 ENG-2459 Back to tika 1.17 as 2.0.0 is not yet released
  pom.xml
Labels: prepared

#47 ENG-2570: Added javax-validator reference
  pom.xml
Labels: approved, prepared

#48 ENG-2459 updating all dependencies
  pom.xml
Labels: prepared

#53 ENG-2459 Downgrading derby and hibernate validator version
  pom.xml
Labels: prepared
